export const defaultColumns = [
  { display: true, key: "cif", label: "cif" },
  { display: true, key: "nombreFantasia", label: "nombreFantasia" },
  { display: true, key: "direccion", label: "direccion" },
  { display: true, key: "localidad", label: "localidad" },
  { display: true, key: "nombreproducto", label: "producto" },
  { display: true, key: "precio", label: "precio" },
  { display: true, key: "precioCosto", label: "precio costo" },
  { display: true, key: "facturar", label: "facturar" },
  { display: true, key: "cpostal", label: "cpostal" },
  { display: false, key: "idruta", label: "idruta" },
  { display: false, key: "codigo", label: "codigo" },
  { display: false, key: "nombre", label: "nombre" },
  { display: false, key: "apellido", label: "apellido" },
  { display: false, key: "cpostal", label: "cpostal" },
  { display: false, key: "provincia", label: "provincia" },
  { display: false, key: "telefono", label: "telefono" },
  { display: false, key: "telefono2", label: "telefono2" },
  { display: false, key: "email", label: "email" },
  { display: true, key: "acciones", label: "acciones" }
];
